<?php

// database/seeders/ExercisesSeeder.php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Exercise;

class ExerciseSeeder extends Seeder
{
    public function run()
    {
        $exercises = [
            ['name' => 'Supino reto com barra', 'category' => 'Força', 'muscle_group' => 'Peito'],
            ['name' => 'Agachamento com barra', 'category' => 'Força', 'muscle_group' => 'Pernas'],
            ['name' => 'Levantamento terra', 'category' => 'Força', 'muscle_group' => 'Costas'],
            ['name' => 'Puxada na frente na polia alta', 'category' => 'Força', 'muscle_group' => 'Costas'],
            ['name' => 'Cadeira extensora', 'category' => 'Força', 'muscle_group' => 'Pernas'],
            ['name' => 'Supino inclinado com halteres', 'category' => 'Força', 'muscle_group' => 'Peito'],
            ['name' => 'Desenvolvimento com halteres', 'category' => 'Força', 'muscle_group' => 'Ombros'],
            ['name' => 'Rosca direta com barra', 'category' => 'Força', 'muscle_group' => 'Bíceps'],
            ['name' => 'Tríceps testa', 'category' => 'Força', 'muscle_group' => 'Tríceps'],
            ['name' => 'Leg press', 'category' => 'Força', 'muscle_group' => 'Pernas'],
            ['name' => 'Cadeira abdutora', 'category' => 'Força', 'muscle_group' => 'Pernas'],
            ['name' => 'Barra fixa', 'category' => 'Força', 'muscle_group' => 'Costas'],
            ['name' => 'Flexão de braço', 'category' => 'Força', 'muscle_group' => 'Peito'],
            ['name' => 'Prancha', 'category' => 'Força', 'muscle_group' => 'Abdômen'],
            ['name' => 'Stiff com barra', 'category' => 'Força', 'muscle_group' => 'Pernas'],
            ['name' => 'Puxada atrás da nuca', 'category' => 'Força', 'muscle_group' => 'Costas'],
            ['name' => 'Abdominal na máquina', 'category' => 'Força', 'muscle_group' => 'Abdômen'],
            ['name' => 'Lunge com halteres', 'category' => 'Força', 'muscle_group' => 'Pernas'],
            ['name' => 'Puxada no pulley', 'category' => 'Força', 'muscle_group' => 'Costas'],
            ['name' => 'Dorsal na polia', 'category' => 'Força', 'muscle_group' => 'Costas'],
            ['name' => 'Bicicleta ergométrica', 'category' => 'Cardio', 'muscle_group' => 'Cardiovascular'],
            ['name' => 'Esteira', 'category' => 'Cardio', 'muscle_group' => 'Cardiovascular'],
            ['name' => 'Kettlebell swing', 'category' => 'Força', 'muscle_group' => 'Pernas'],
            ['name' => 'Abdominal com rosca', 'category' => 'Força', 'muscle_group' => 'Abdômen'],
            ['name' => 'Halteres em rosca', 'category' => 'Força', 'muscle_group' => 'Bíceps'],
            ['name' => 'Flexão de tríceps no banco', 'category' => 'Força', 'muscle_group' => 'Tríceps'],
            ['name' => 'Desenvolvimento com barra', 'category' => 'Força', 'muscle_group' => 'Ombros'],
            ['name' => 'Agachamento sumô', 'category' => 'Força', 'muscle_group' => 'Pernas'],
            ['name' => 'Bicicleta ergométrica HIIT', 'category' => 'Cardio', 'muscle_group' => 'Cardiovascular'],
            ['name' => 'Tríceps no pulley', 'category' => 'Força', 'muscle_group' => 'Tríceps'],
            ['name' => 'Abdominal oblíquo', 'category' => 'Força', 'muscle_group' => 'Abdômen'],
            ['name' => 'Rosca martelo', 'category' => 'Força', 'muscle_group' => 'Bíceps'],
            ['name' => 'Flexão de braço com halteres', 'category' => 'Força', 'muscle_group' => 'Peito'],
            ['name' => 'Desenvolvimento Arnold', 'category' => 'Força', 'muscle_group' => 'Ombros'],
            ['name' => 'Série de agachamento livre', 'category' => 'Força', 'muscle_group' => 'Pernas'],
            ['name' => 'Máquina de glúteo', 'category' => 'Força', 'muscle_group' => 'Pernas'],
            ['name' => 'Barra paralela', 'category' => 'Força', 'muscle_group' => 'Tríceps'],
            ['name' => 'Cadeira flexora', 'category' => 'Força', 'muscle_group' => 'Pernas'],
            ['name' => 'Caminhada inclinada', 'category' => 'Cardio', 'muscle_group' => 'Cardiovascular'],
            ['name' => 'Puxada com corda', 'category' => 'Força', 'muscle_group' => 'Costas'],
            ['name' => 'Abdominal com bola suíça', 'category' => 'Força', 'muscle_group' => 'Abdômen'],
            ['name' => 'Treinamento funcional', 'category' => 'Força', 'muscle_group' => 'Corpo todo'],
            ['name' => 'Escada', 'category' => 'Cardio', 'muscle_group' => 'Cardiovascular'],
            ['name' => 'Máquina de leg press 45°', 'category' => 'Força', 'muscle_group' => 'Pernas'],
            ['name' => 'Caminhada rápida', 'category' => 'Cardio', 'muscle_group' => 'Cardiovascular'],
            ['name' => 'Pular corda', 'category' => 'Cardio', 'muscle_group' => 'Cardiovascular'],
            ['name' => 'Puxada no cross-over', 'category' => 'Força', 'muscle_group' => 'Costas'],
            ['name' => 'Flexão de braços em barra', 'category' => 'Força', 'muscle_group' => 'Peito'],
            ['name' => 'Tríceps francês com halteres', 'category' => 'Força', 'muscle_group' => 'Tríceps'],
            ['name' => 'Agachamento com kettlebell', 'category' => 'Força', 'muscle_group' => 'Pernas'],
            ['name' => 'Dorsal com barra', 'category' => 'Força', 'muscle_group' => 'Costas'],
            ['name' => 'Remada unilateral', 'category' => 'Força', 'muscle_group' => 'Costas'],
            ['name' => 'Lateral raise com halteres', 'category' => 'Força', 'muscle_group' => 'Ombros'],
            ['name' => 'Deadlift', 'category' => 'Força', 'muscle_group' => 'Costas'],
            ['name' => 'Abdominal com disco', 'category' => 'Força', 'muscle_group' => 'Abdômen'],
            ['name' => 'Correr ao ar livre', 'category' => 'Cardio', 'muscle_group' => 'Cardiovascular'],
            ['name' => 'Barra com pegada pronada', 'category' => 'Força', 'muscle_group' => 'Costas'],
            ['name' => 'Giro de quadril com kettlebell', 'category' => 'Força', 'muscle_group' => 'Pernas'],
            ['name' => 'Cadeira adutora', 'category' => 'Força', 'muscle_group' => 'Pernas'],
            ['name' => 'Corrida de alta intensidade', 'category' => 'Cardio', 'muscle_group' => 'Cardiovascular'],
            ['name' => 'Abdominal no banco inclinado', 'category' => 'Força', 'muscle_group' => 'Abdômen'],
            ['name' => 'Squat jump', 'category' => 'Força', 'muscle_group' => 'Pernas'],
            ['name' => 'Exercício no aparelho de remo', 'category' => 'Cardio', 'muscle_group' => 'Cardiovascular'],
            ['name' => 'Lunges na barra', 'category' => 'Força', 'muscle_group' => 'Pernas'],
            ['name' => 'Flexão de braço no banco', 'category' => 'Força', 'muscle_group' => 'Peito'],
            ['name' => 'Pullover com barra', 'category' => 'Força', 'muscle_group' => 'Peito'],
            ['name' => 'Abdominal com perna estendida', 'category' => 'Força', 'muscle_group' => 'Abdômen'],
            ['name' => 'Jumping jacks', 'category' => 'Cardio', 'muscle_group' => 'Cardiovascular'],
            ['name' => 'Giro com kettlebell', 'category' => 'Força', 'muscle_group' => 'Core'],
            ['name' => 'Glúteo com cabo', 'category' => 'Força', 'muscle_group' => 'Pernas'],
            ['name' => 'Barra paralela', 'category' => 'Força', 'muscle_group' => 'Tríceps'],
            ['name' => 'Remada baixa', 'category' => 'Força', 'muscle_group' => 'Costas'],
            ['name' => 'Kettlebell clean and press', 'category' => 'Força', 'muscle_group' => 'Ombros'],
            ['name' => 'Deadlift com kettlebell', 'category' => 'Força', 'muscle_group' => 'Pernas'],
            ['name' => 'Tríceps na máquina', 'category' => 'Força', 'muscle_group' => 'Tríceps'],
            ['name' => 'Puxada no cross-over', 'category' => 'Força', 'muscle_group' => 'Costas'],
            // Força
            ['name' => 'Supino reto com barra', 'category' => 'Força', 'muscle_group' => 'Peito'],
            ['name' => 'Supino inclinado com halteres', 'category' => 'Força', 'muscle_group' => 'Peito'],
            ['name' => 'Supino declinado com barra', 'category' => 'Força', 'muscle_group' => 'Peito'],
            ['name' => 'Agachamento com barra', 'category' => 'Força', 'muscle_group' => 'Pernas'],
            ['name' => 'Afundo com halteres', 'category' => 'Força', 'muscle_group' => 'Pernas'],
            ['name' => 'Levantamento terra', 'category' => 'Força', 'muscle_group' => 'Costas'],
            ['name' => 'Rosca direta com barra', 'category' => 'Força', 'muscle_group' => 'Bíceps'],
            ['name' => 'Rosca martelo com halteres', 'category' => 'Força', 'muscle_group' => 'Bíceps'],
            ['name' => 'Rosca concentrada com haltere', 'category' => 'Força', 'muscle_group' => 'Bíceps'],
            ['name' => 'Tríceps testa com barra', 'category' => 'Força', 'muscle_group' => 'Tríceps'],
            ['name' => 'Tríceps francês com halteres', 'category' => 'Força', 'muscle_group' => 'Tríceps'],
            ['name' => 'Tríceps pulley', 'category' => 'Força', 'muscle_group' => 'Tríceps'],
            ['name' => 'Remada unilateral com haltere', 'category' => 'Força', 'muscle_group' => 'Costas'],
            ['name' => 'Remada curvada com barra', 'category' => 'Força', 'muscle_group' => 'Costas'],
            ['name' => 'Puxada na frente', 'category' => 'Força', 'muscle_group' => 'Costas'],
            ['name' => 'Puxada atrás', 'category' => 'Força', 'muscle_group' => 'Costas'],
            ['name' => 'Flexão de braço', 'category' => 'Força', 'muscle_group' => 'Peito'],
            ['name' => 'Flexão de braço com elevação de perna', 'category' => 'Força', 'muscle_group' => 'Peito'],
            ['name' => 'Prancha com pés elevados', 'category' => 'Força', 'muscle_group' => 'Core'],
            ['name' => 'Prancha lateral', 'category' => 'Força', 'muscle_group' => 'Core'],
            ['name' => 'Prancha com um braço', 'category' => 'Força', 'muscle_group' => 'Core'],
            ['name' => 'Bola medicinal (Lançamento)', 'category' => 'Força', 'muscle_group' => 'Pernas'],
            ['name' => 'Bola medicinal (Giro de tronco)', 'category' => 'Força', 'muscle_group' => 'Core'],
            ['name' => 'Agachamento com caneleiras', 'category' => 'Força', 'muscle_group' => 'Pernas'],
            ['name' => 'Leg press com caneleiras', 'category' => 'Força', 'muscle_group' => 'Pernas'],
            ['name' => 'Step-up com halteres', 'category' => 'Força', 'muscle_group' => 'Pernas'],
            ['name' => 'Agachamento sumô com halteres', 'category' => 'Força', 'muscle_group' => 'Pernas'],
            ['name' => 'Elevação de quadril com barra', 'category' => 'Força', 'muscle_group' => 'Glúteos'],
            ['name' => 'Elevação de quadril com halteres', 'category' => 'Força', 'muscle_group' => 'Glúteos'],
            ['name' => 'Extensão de pernas', 'category' => 'Força', 'muscle_group' => 'Pernas'],
            ['name' => 'Flexão de pernas', 'category' => 'Força', 'muscle_group' => 'Pernas'],
            ['name' => 'Abdominal com rolo', 'category' => 'Força', 'muscle_group' => 'Abdômen'],
            ['name' => 'Abdominal supra', 'category' => 'Força', 'muscle_group' => 'Abdômen'],
            ['name' => 'Abdominal infra', 'category' => 'Força', 'muscle_group' => 'Abdômen'],
            ['name' => 'Abdominal oblíquo', 'category' => 'Força', 'muscle_group' => 'Abdômen'],
            ['name' => 'Abdominal com bola', 'category' => 'Força', 'muscle_group' => 'Abdômen'],
            ['name' => 'Exercício de TRX para peito', 'category' => 'Força', 'muscle_group' => 'Peito'],
            ['name' => 'Exercício de TRX para costas', 'category' => 'Força', 'muscle_group' => 'Costas'],
            ['name' => 'Exercício de TRX para pernas', 'category' => 'Força', 'muscle_group' => 'Pernas'],
            ['name' => 'Exercício de TRX para core', 'category' => 'Força', 'muscle_group' => 'Core'],
            ['name' => 'Exercício de TRX com caneleiras para pernas', 'category' => 'Força', 'muscle_group' => 'Pernas'],
            ['name' => 'Puxada com TRX', 'category' => 'Força', 'muscle_group' => 'Costas'],
            ['name' => 'Mergulho com TRX', 'category' => 'Força', 'muscle_group' => 'Tríceps'],
            // Cardio
            ['name' => 'Corrida na esteira', 'category' => 'Cardio', 'muscle_group' => 'Cardio'],
            ['name' => 'Ciclismo', 'category' => 'Cardio', 'muscle_group' => 'Cardio'],
            ['name' => 'Pular corda', 'category' => 'Cardio', 'muscle_group' => 'Cardio'],
            ['name' => 'Corda naval', 'category' => 'Cardio', 'muscle_group' => 'Cardio'],
            ['name' => 'Burpees', 'category' => 'Cardio', 'muscle_group' => 'Cardio'],
            ['name' => 'Mountain climbers', 'category' => 'Cardio', 'muscle_group' => 'Cardio'],
            ['name' => 'Jumping jacks', 'category' => 'Cardio', 'muscle_group' => 'Cardio'],
            ['name' => 'Kettlebell swing', 'category' => 'Cardio', 'muscle_group' => 'Cardio'],
            ['name' => 'Box jump', 'category' => 'Cardio', 'muscle_group' => 'Cardio'],
            ['name' => 'Saltos no step', 'category' => 'Cardio', 'muscle_group' => 'Cardio'],
            // Flexibilidade
            ['name' => 'Alongamento de quadril', 'category' => 'Flexibilidade', 'muscle_group' => 'Pernas'],
            ['name' => 'Alongamento de isquiotibiais', 'category' => 'Flexibilidade', 'muscle_group' => 'Pernas'],
            ['name' => 'Alongamento de peito', 'category' => 'Flexibilidade', 'muscle_group' => 'Peito'],
            ['name' => 'Alongamento de tríceps', 'category' => 'Flexibilidade', 'muscle_group' => 'Tríceps'],
            ['name' => 'Alongamento de costas', 'category' => 'Flexibilidade', 'muscle_group' => 'Costas'],
            ['name' => 'Alongamento de ombro', 'category' => 'Flexibilidade', 'muscle_group' => 'Ombros'],
            ['name' => 'Alongamento de panturrilhas', 'category' => 'Flexibilidade', 'muscle_group' => 'Pernas'],
            // Mais Exercícios
            ['name' => 'Agachamento com bola medicinal', 'category' => 'Força', 'muscle_group' => 'Pernas'],
            ['name' => 'Lançamento de bola medicinal', 'category' => 'Força', 'muscle_group' => 'Peito'],
            ['name' => 'Exercício de abdominais com bola medicinal', 'category' => 'Força', 'muscle_group' => 'Abdômen'],
            ['name' => 'Bicicleta no ar', 'category' => 'Cardio', 'muscle_group' => 'Cardio'],
            ['name' => 'Twist com bola medicinal', 'category' => 'Força', 'muscle_group' => 'Core'],
        ];

        foreach ($exercises as $exercise) {
            Exercise::create($exercise);
        }
    }
}
